github_repo_url: ""
github_pat: ""
cloudflare_api_token: ""
cloudflare_account_id: ""
cloudflare_tunnel_token: ""
cloudflare_tunnel_name: ""
grafana_admin_user: ""
grafana_admin_password: ""
slack_api_url: ""